### ISSUE TITLE
Can not reproduce ColBERT-QA1 results on NQ

### ISSUE THREAD

**Issue by alexlimh** [stanfordnlp/ColBERT-QA#1]
Hi Omar,

Recently I was trying to reproduce ColBERT-QA on NQ but I can't get the results reported in Table 1 for the ColBERT-QA1 model. The best success@20 I got is 77.8, which is even lower than DPR. I'm wondering whether you could share your training data on NQ and Trivia so that I could replicate your results. Thanks a lot

**Comment by santhnm2** [comment]
Hi @alexlimh, Omar is currently wrapping up an internship so he will be available to help you in a couple weeks. In the meantime, I've uploaded the ColBERT-QA1 NQ checkpoint here*: https://drive.google.com/file/d/1tlASVNpeQeQF2dfdJiuNBjhfJgu6wSDB/view?usp=sharing
Could you also share the specific steps you took to set up your experiment? Other teams have had success with reproducing the results so perhaps there's something missing from your experiment that we could help identify.

* Please let me know when you have downloaded the file so I can remove it afterwards since we have limited space. However, we will have a full public release of the checkpoints soon.

**Comment by alexlimh** [comment]
Hi @santhnm2,

Thanks for the quick response! I would actually love to reproduce the training results of ColBERT-QA1 from scratch and play with the training hyperparameters a bit. I'm currently using the [DPR](https://github.com/facebookresearch/DPR) training data and here's the hyperparameter settings I used: 
```
task:
  shared_model: false
  warmup_steps: 1237
  model:
    model_path: bert-base-uncased
    projection_dim: 128
    dropout: 0.1
  transform:
    max_seq_len: 256
  optim:
    _target_: torch.optim.AdamW
    lr: 2.0e-05
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-08
    weight_decay: 0
    amsgrad: false
datamodule:
  batch_size: 16 # total is 16 x 8 = 128
  num_negative: 1
  use_title: true
trainer:
  gpus: 8
  num_nodes: 1
  max_epochs: 40
  gradient_clip_val: 2.0
  strategy: ddp
  precision: 16 
```
I know it is not completely the same training setting as described in the paper, but I used this setting to reproduce the ColBERT's results on MS MARCO passages successfully. Therefore I thought under the same setting, the numbers on NQ should also be closed to the paper's but it's not. The biggest difference is that I used the training data from DPR while ColBERT-QA constructed the training data from scratch using Anserini. Could you share the training data you used or tell me what might went wrong with my current hyperparameters setting on NQ?
